

services:
  backend:
    build:
      context: ./react-node-mysql-backend
    ports:
      - "5000:5000"
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: admin
      DB_NAME: userdb
      DB_PORT: 3306

  frontend:
    build:
      context: frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend

  mysql:
    image: mysql:latest
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: userdb
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
